version: '3.8'

services:
  finance-backend:
    image: 552509717559.dkr.ecr.us-east-1.amazonaws.com/personal-finance-tracker-backend:latest
    container_name: finance-backend-prod
    restart: always
    ports:
      - "5001:5001"
    environment:
      DB_HOST: db-finance-tracker.cwholn2fehh0.us-east-1.rds.amazonaws.com
      DB_PORT: 3306
      DB_USER: admin
      DB_PASSWORD: "21102005"
      DB_NAME: finance_tracker

  finance-frontend:
    image: 552509717559.dkr.ecr.us-east-1.amazonaws.com/personal-finance-tracker-frontend:latest
    container_name: finance-frontend-prod
    restart: always
    ports:
      - "3001:3001"
    environment:
      VITE_APP_BACKEND_URL: "http://98.91.108.120:5001"