apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-frontend
  namespace: finance-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finance-frontend
  template:
    metadata:
      labels:
        app: finance-frontend
    spec:
      containers:
      - name: frontend
        image: 552509717559.dkr.ecr.us-east-1.amazonaws.com/personal-finance-tracker-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001 # Khớp chính xác với cổng EXPOSE 3001 của frontend Dockerfile
        env:
        - name: VITE_API_URL # Đổi từ REACT_APP sang VITE để Vite nhận diện được biến môi trường
          value: "http://98.91.108.120:5001"
---
apiVersion: v1
kind: Service
metadata:
  name: finance-frontend-service
  namespace: finance-apps
spec:
  type: NodePort
  ports:
  - port: 3001
    targetPort: 3001
    nodePort: 32001 # Cổng truy cập ngoài Internet: http://98.91.108.120:32001
  selector:
    app: finance-frontend