apiVersion: v1
kind: Secret
metadata:
  name: finance-secret
  namespace: finance-apps
type: Opaque

stringData:
  DB_HOST: "db-finance-tracker.cwholn2fehh0.us-east-1.rds.amazonaws.com"
  DB_PORT: "3306"
  DB_USER: "admin"
  DB_PASSWORD: "21102005"
  DB_NAME: "finance_tracker"

  SECRET_KEY: "change-this-secret-key"

  JWT_SECRET_KEY: "change-this-jwt-secret"